FROM python:3.12.5-bookworm

RUN pip install requests>= 2.26.0
RUN pip install beautifulsoup4>=4.10.0
RUN pip install asyncio==3.4.3
RUN pip install lxml>=4.6.3
RUN pip install typed-astunparse>=2.1.4
RUN pip install tensorflow-hub==0.12.0
RUN pip install Django==3.1.5
RUN pip install pytz==2022.1
RUN pip install line-profiler==1.0b3
RUN pip install opencv-python==4.10.0.84
RUN pip install black==22.12.0
RUN pip install certifi==2022.12.7
RUN pip install chardet==5.1.0
RUN pip install charset-normalizer==3.1.0

RUN wget https://github.com/jgm/pandoc/releases/download/3.4/pandoc-3.4-1-amd64.deb \
    && dpkg -i pandoc-3.4-1-amd64.deb \
    && rm -f pandoc-3.4-1-amd64.deb













